name: apula_responder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core UI and utilities
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  lottie: ^3.1.2
  local_auth: ^2.2.0
  mobile_scanner: ^6.0.2
  audioplayers: ^6.0.0

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3

  # Notifications
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.0.1

  # Maps + Navigation
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  flutter_tts: ^4.0.0
  http: ^1.2.1

  # Optional map alternative
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # External apps & links
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/responder_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/responder_logo.png
    - assets/check orange.json
    - assets/fireloading.json
    - assets/apula-icon.png
    - assets/apula_home_icon.png
    - assets/sounds/fire_alarm.mp3
    - assets/examples/fire_example.jpg
    - assets/examples/profile_pic.jpg
    - assets/examples/thermal_example.png
    - assets/fire_pin.png
    - assets/responder_pin.png
